on:
  push:
    branches:
      - dev
  schedule:
    - cron: '0 9,17 * * *'

env:
  AMH_EL_TTS_API: ${{ secrets.AMH_EL_TTS_API }}
  TG_EL_TTS_API: ${{ secrets.TG_EL_TTS_API }}
  RSS_API: ${{ secrets.RSS_API }}
  PERSONAL_EL_API: ${{ secrets.PERSONAL_EL_API }}
  NN_EL_API: ${{ secrets.NN_EL_API }}
  EXTRA_EL_API_1: ${{ secrets.EXTRA_EL_API_1 }}
  CLIENT_SECRET_HED: ${{ secrets.CLIENT_SECRET_HED }}
  TOKEN_SECRET_HED: ${{ secrets.TOKEN_SECRET_HED }}
  HED_GEM_API: ${{ secrets.HED_GEM_API }}
  HED_EL_API: ${{ secrets.HED_EL_API }}
  HED_PEXELS_API: ${{ secrets.HED_PEXELS_API }}

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script HED
        run: python hadith-personal/youtube_upload.py


