on:
#  push:
#    branches:
#      - dev
#  schedule:
#    - cron: '0 4,12 * * *'

env:
  AMH_EL_TTS_API: ${{ secrets.AMH_EL_TTS_API }}
  TG_EL_TTS_API: ${{ secrets.TG_EL_TTS_API }}
  AMH_GEM_API: ${{ secrets.AMH_GEM_API }}
  AMH_PEXELS_API: ${{ secrets.AMH_PEXELS_API }}
  CLIENT_SECRET_KEY: ${{ secrets.CLIENT_SECRET_KEY }}
  TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
  RSS_API: ${{ secrets.RSS_API }}
  PERSONAL_EL_API: ${{ secrets.PERSONAL_EL_API }}
  CLIENT_SECRET_NN: ${{ secrets.CLIENT_SECRET_NN }}
  NN_GEM_API: ${{ secrets.NN_GEM_API }}
  NN_EL_API: ${{ secrets.NN_EL_API }}
  NN_PEXELS_API: ${{ secrets.NN_PEXELS_API }}
  TOKEN_SECRET_NN: ${{ secrets.TOKEN_SECRET_NN }}
  EXTRA_EL_API_1: ${{ secrets.EXTRA_EL_API_1 }}
  TEST_EL_API: ${{ secrets.TEST_EL_API }}
  PERSOANL_EL_API_2: ${{ secrets.PERSOANL_EL_API_2 }}

jobs:
#  run-app-amh:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.13'
#
#      - name: Install FFmpeg
#        run: sudo apt-get update && sudo apt-get install -y ffmpeg
#
#      - name: Install dependencies
#        run: pip install -r requirements.txt
#
#      - name: Run script amh
#        run: python aimoneyhacks-personal/api/youtube_upload.py

  run-app-nn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script nn
        run: python nightmarenarrator-personal/api/youtube_upload.py


